### ISSUE TITLE
Consider moving to use Express-session instead of accessing req.session

### ISSUE THREAD

**Issue by look4regev** [look4regev/dominoes-node-react-game#14]
In the backend we req.session instead of using the managed Express-session package. It might indicate on something we are missing.

**Comment by amirkeren** [comment]
Not sure I understand what you mean.. It's working fine isn't it?

**Comment by look4regev** [comment]
Yep, hasn't find any specific issue yet, it's just that Ofer mentioned using `Express-session` so made this issue just to verify that we are not missing anything with the session management.

**Comment by look4regev** [comment]
No need to invest here. Working great as is.
